export interface CycleStep {
  id: string;
  title: string;
  objective: string;
  questions: string[];
  lookFor: string;
  effect: string;
  mistake: string;
  role: string;
}

export const cycleSteps: CycleStep[] = [
  {
    id: "analyse",
    title: "Analyse de l'appel d'offres",
    objective: "Comprendre ce qui est demandé avant de chiffrer.",
    questions: ["Qui est le client ?", "Quel navire ?", "Quelle est la date limite ?", "Quels documents manquent ?"],
    lookFor: "Page de garde, objet, pièces jointes citées mais absentes.",
    effect: "Une mauvaise lecture se répercute sur tous les coûts.",
    mistake: "Commencer le chiffrement avant d'avoir listé les pièces manquantes.",
    role: "NavalSmart propose une lecture. L'estimateur confirme chaque extrait.",
  },
  {
    id: "portee",
    title: "Définition de la portée",
    objective: "Dire ce qui est inclus et ce qui ne l'est pas.",
    questions: ["Quels systèmes sont touchés ?", "Quelles exclusions sont écrites ?"],
    lookFor: "Verbes de travaux : remplacer, déposer, installer, essayer, peindre.",
    effect: "La portée fixe le périmètre du prix.",
    mistake: "Ajouter un système qui n'est pas dans le document sans le noter comme hypothèse.",
    role: "Les éléments de portée doivent citer une page lorsqu'ils viennent du document.",
  },
  {
    id: "decoupage",
    title: "Découpage des travaux",
    objective: "Transformer la portée en lots que l'on peut chiffrer.",
    questions: ["Quel lot porte cette tâche ?", "L'ordre des travaux est-il logique ?"],
    lookFor: "Coque, mécanique, électricité, tuyauterie, peinture, logistique.",
    effect: "Un lot oublié devient un oubli de coût.",
    mistake: "Mélanger fabrication et installation dans une seule ligne impossible à vérifier.",
    role: "Les lots proposés restent modifiables, supprimables et réorganisables.",
  },
  {
    id: "quantification",
    title: "Quantification",
    objective: "Associer une quantité et une unité à chaque tâche.",
    questions: ["La quantité est-elle écrite ?", "L'unité est-elle claire ?", "Faut-il un relevé ?"],
    lookFor: "Heures, tonnes, mètres, surfaces, forfaits.",
    effect: "Le prix unitaire n'a de sens qu'avec une quantité.",
    mistake: "Inventer une quantité et la présenter comme issue du document.",
    role: "Si la quantité est absente, NavalSmart doit l'indiquer comme manquante.",
  },
  {
    id: "labor",
    title: "Main-d'œuvre",
    objective: "Estimer les heures et les taux par métier.",
    questions: ["Les heures sont-elles totales ou par personne ?", "Le taux vient-il d'où ?"],
    lookFor: "Métiers cités, quarts, accès difficile, productivité.",
    effect: "Heures × taux × nombre de travailleurs, puis heures supplémentaires.",
    mistake: "Multiplier des heures déjà totales par le nombre de travailleurs.",
    role: "Le logiciel calcule. Il n'invente pas le taux si le document ne le donne pas.",
  },
  {
    id: "materiaux",
    title: "Matériaux",
    objective: "Chiffrer ce qui est acheté, transporté et perdu.",
    questions: ["Quel fournisseur ?", "Quelle validité de prix ?", "Quelles pertes ?"],
    lookFor: "Nuances, épaisseurs, quantités, incotermes.",
    effect: "Quantité × prix unitaire + transport + pertes.",
    mistake: "Oublier le transport ou présenter un prix non reçu comme confirmé.",
    role: "Le statut du fournisseur rappelle si le prix est demandé, reçu ou validé.",
  },
  {
    id: "equipements",
    title: "Équipements",
    objective: "Compter la location et la mobilisation du matériel.",
    questions: ["Quelle durée ?", "Quel taux ?", "Le transport est-il inclus ?"],
    lookFor: "Grues, échafaudages, machines à souder, nacelles.",
    effect: "Quantité × durée × taux + transport.",
    mistake: "Oublier la durée de mobilisation entre deux phases.",
    role: "L'équipement reste une ligne vérifiable, distincte de la main-d'œuvre.",
  },
  {
    id: "sous-traitance",
    title: "Sous-traitance",
    objective: "Isoler les travaux confiés à un tiers.",
    questions: ["Quel lot ?", "Que comprend le prix ?", "Que reste-t-il à notre charge ?"],
    lookFor: "Contrôles, spécialités, échafaudages spécialisés, traitements.",
    effect: "Le prix du sous-traitant entre dans le coût direct, sans être recalculé par l'IA.",
    mistake: "Compter deux fois le même travail en heures internes et en sous-traitance.",
    role: "L'association à un lot rend le double compte visible.",
  },
  {
    id: "fournisseurs",
    title: "Fournisseurs",
    objective: "Appuyer les prix sur des soumissions comparables.",
    questions: ["Devise ?", "Validité ?", "Délai ?", "Inclus et exclus ?"],
    lookFor: "Offres écrites, et non des souvenirs de prix.",
    effect: "Un prix non reçu reste une information manquante.",
    mistake: "Comparer deux offres qui n'ont pas le même périmètre.",
    role: "NavalSmart conserve le statut et le document, il ne choisit pas le fournisseur.",
  },
  {
    id: "risques",
    title: "Risques",
    objective: "Nommer ce qui peut faire varier le coût ou le délai.",
    questions: ["Quelle phrase du document justifie ce risque ?", "Quelle mitigation ?"],
    lookFor: "Pénalités, accès, matières dangereuses, informations absentes.",
    effect: "La provision est un pourcentage choisi par l'estimateur, appliqué par le moteur.",
    mistake: "Ajouter un risque générique sans lien avec le dossier.",
    role: "Un risque sans justification suffisante ne doit pas être proposé comme un fait.",
  },
  {
    id: "hypotheses",
    title: "Hypothèses",
    objective: "Écrire ce que l'on suppose pour pouvoir chiffrer.",
    questions: ["Que se passe-t-il si l'hypothèse est fausse ?", "Qui peut la confirmer ?"],
    lookFor: "Disponibilité du navire, quantités provisoires, taux de simulation.",
    effect: "Une hypothèse explique un chiffre. Elle ne le transforme pas en fait.",
    mistake: "Laisser une hypothèse seulement dans sa tête.",
    role: "Chaque hypothèse a une source, un impact et un statut.",
  },
  {
    id: "consolidation",
    title: "Consolidation des coûts",
    objective: "Additionner les postes sans double compte.",
    questions: ["Chaque montant a-t-il une source ?", "Les paramètres de marge sont-ils ceux voulus ?"],
    lookFor: "Direct, indirect, provision, coût estimé, prix proposé.",
    effect: "Le moteur applique les pourcentages saisis. L'IA ne fait pas cette arithmétique.",
    mistake: "Modifier un total à la main au lieu de corriger la quantité ou le taux.",
    role: "Les totaux affichés sont des calculs système, toujours recomposables.",
  },
  {
    id: "revue",
    title: "Revue",
    objective: "Chercher les incohérences avant de figer l'estimation.",
    questions: ["Quel poste est encore généré par l'IA ?", "Quel prix n'a pas de source ?"],
    lookFor: "Doublons, quantités nulles, taux extrêmes, risques sans mitigation.",
    effect: "La revue prépare la décision. Elle ne valide pas à la place de l'estimateur.",
    mistake: "Traiter une alerte comme une correction déjà faite.",
    role: "Chaque recommandation peut être acceptée, ignorée ou annotée.",
  },
  {
    id: "soumission",
    title: "Soumission",
    objective: "Présenter un prix que l'on peut expliquer.",
    questions: ["Quelles réserves ?", "Quelles pièces manquent encore ?"],
    lookFor: "Couverture, portée, coûts, risques, hypothèses, manques, note de validation.",
    effect: "Le rapport rend visible ce qui est vérifié et ce qui ne l'est pas.",
    mistake: "Masquer les informations manquantes dans la version remise.",
    role: "Le rapport exporte les données du projet. Il n'embellit pas les trous.",
  },
];
